# Generated by Django 4.2.22 on 2025-06-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='cpf',
            field=models.CharField(error_messages={'blank': 'CPF é obrigatório.', 'invalid': 'CPF inválido.', 'unique': 'CPF já está cadastrado.'}, help_text='CPF do usuário (somente números)', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'O e-mail é obrigatório.', 'invalid': 'Formato de e-mail inválido.', 'unique': 'Este e-mail já está cadastrado.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
