# Generated by Django 4.2.22 on 2025-06-07 00:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('blockchain_balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=20)),
                ('virtual_balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='PENDING', max_length=10)),
                ('tx_type', models.CharField(choices=[('REWARD', 'Recompensa'), ('WITHDRAW', 'Saque')], default='REWARD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
