# Generated by Django 4.2.22 on 2025-06-07 01:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blockchain_balance',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.0'), help_text='Saldo na blockchain', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='virtual_balance',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.0'), help_text='Saldo local antes de mintar tokens', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Endereço da carteira blockchain do usuário.', max_length=42, null=True),
        ),
    ]
