# Generated by Django 4.2.22 on 2025-06-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='expiration_date',
        ),
    ]
