openapi: 3.0.3
info:
  title: API de Autenticação - FeedToken
  version: 1.0.0
  description: |
    Endpoints para login e registro de usuários comuns e empresas.

paths:
  /login/:
    post:
      summary: Login do usuário
      description: Autenticação de usuários (CommonUser e Company)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: usuario@example.com
                password:
                  type: string
                  example: SenhaForte123
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                    description: Token de autenticação JWT ou de sessão
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
        '400':
          description: Dados inválidos
          content:
            application/json:
              example:
                email: ["Este campo é obrigatório."]
                password: ["Este campo é obrigatório."]
        '401':
          description: Credenciais incorretas
          content:
            application/json:
              example:
                detail: Não foi possível fazer login com as credenciais fornecidas.

  /register/common/:
    post:
      summary: Registro de usuário comum
      description: Cria um usuário comum (CommonUser)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password1
                - password2
                - full_name
                - cpf
              properties:
                email:
                  type: string
                  format: email
                  example: usuario@example.com
                password1:
                  type: string
                  example: SenhaForte123
                password2:
                  type: string
                  example: SenhaForte123
                full_name:
                  type: string
                  example: João da Silva
                cpf:
                  type: string
                  example: 53560671000
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              example:
                email: usuario@example.com
                full_name: João da Silva
                cpf: 53560671000
        '400':
          description: Erros de validação ou e-mail já cadastrado
          content:
            application/json:
              examples:
                email_invalido:
                  value:
                    email: ["Por favor, insira um endereço de e-mail válido."]
                cpf_invalido:
                  value:
                    cpf: ["CPF inválido."]
                senhas_nao_conferem:
                  value:
                    password1: ["As senhas não conferem."]
                email_duplicado:
                  value:
                    email: ["Este endereço de e-mail já está em uso."]
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              example:
                detail: Erro interno do servidor.

  /register/company/:
    post:
      summary: Registro de empresa
      description: Registra uma empresa (Company)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password1
                - password2
                - commercial_name
                - legal_name
                - business_area
                - cnpj
              properties:
                email:
                  type: string
                  format: email
                  example: empresa@exemplo.com
                password1:
                  type: string
                  example: SenhaForte123
                password2:
                  type: string
                  example: SenhaForte123
                commercial_name:
                  type: string
                  example: Empresa Exemplo
                legal_name:
                  type: string
                  example: Empresa Exemplo LTDA
                business_area:
                  type: string
                  example: Tecnologia
                cnpj:
                  type: string
                  example: 84480679000153
                website:
                  type: string
                  format: uri
                  example: https://empresa.com.br
                  nullable: true
                logo_url:
                  type: string
                  format: uri
                  example: https://empresa.com.br/logo.png
                  nullable: true
                corporate_tax_id:
                  type: string
                  example: 123456789
                  nullable: true
      responses:
        '201':
          description: Empresa criada com sucesso
          content:
            application/json:
              example:
                email: empresa@exemplo.com
                commercial_name: Empresa Exemplo
                legal_name: Empresa Exemplo LTDA
                business_area: Tecnologia
                cnpj: 84480679000153
                website: https://empresa.com.br
                logo_url: https://empresa.com.br/logo.png
                corporate_tax_id: 123456789
        '400':
          description: Erros de validação, e-mail ou CNPJ já cadastrado
          content:
            application/json:
              examples:
                email_invalido:
                  value:
                    email: ["Por favor, insira um endereço de e-mail válido."]
                cnpj_invalido:
                  value:
                    cnpj: ["CNPJ inválido."]
                senhas_nao_conferem:
                  value:
                    password1: ["As senhas não conferem."]
                email_duplicado:
                  value:
                    email: ["Este endereço de e-mail já está em uso."]
                cnpj_duplicado:
                  value:
                    cnpj: ["Este CNPJ já está em uso."]
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              example:
                detail: Erro interno do servidor.
