# Generated by Django 4.2.22 on 2025-06-08 18:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenwallet',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=36),
        ),
    ]
